title: Your awesome title
author: A Cool Human
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

bootstrap:
  date_format: "%b %-d, %Y"
  header_menu:
    - url: about.md
      Submenu:
      - title: Subpage
        url: about.md

theme: bootstrap-5

plugins:
 - jekyll-feed
 - jekyll-seo-tag
